### ISSUE TITLE
Missing compatibility with ke_search 4.0 

### ISSUE THREAD

**Issue by tillschweneker** [Gregor-Agnes/mask_kesearch_indexer#8]
The namespace of ke_search has changed to `Tpwd\KeSearch` with version 4.

Can you please update the extension so it works with the new version?

Thanks

**Comment by Gregor-Agnes** [comment]
Hi, thx for the hint. I will look into it in the next version. Very busy a t the moment.

**Comment by EvilBMP** [comment]
Simply replace the following line in the composer.json

`"teaminmedias-pluswerk/ke_search": "^3.6.0",`

with

`"tpwd/ke_search": "^3.6 || ^4.0",`

IMHO then tag a new release as version 2.0.0 because of the "soft-breaking change" in the requires. I think a version 1.7.0 may lead to errors, if people have `"zwo3/mask_kesearch_indexer": "^1.6",` as required package in their main composer.json. But that's just my opinion and I'm open for a discussion on that ;-)

**Comment by Gregor-Agnes** [comment]
Yeah, these are the things I will have to check and test. As said, feel free to do all that and create a pull request, if you depend on getting it fast.
